// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsvjttarilbvdomepdrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdmp0dGFyaWxidmRvbWVwZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODY0MjUsImV4cCI6MjA3Mzk2MjQyNX0.Vxo89wo3iNizCIdUFPzRD87ed-sMB6ER0wN_rUPSCCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});